services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - backend

  app:
    build:
      context: .
      # args:
      #   ENV_VAR_NEEDED_AT_BUILD_TIME: ${ENV_VAR_NEEDED_AT_BUILD_TIME}
    restart: unless-stopped
    # env will be loaded at runtime
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge